# Generated by Django 4.2.6 on 2023-10-31 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_connection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="update",
            new_name="updated",
        ),
    ]
